# Generated by Django 4.1.5 on 2023-01-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_currency_user_gender_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
