# Generated by Django 4.1.5 on 2023-01-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity", options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="amenity", old_name="update", new_name="update_at",
        ),
        migrations.RenameField(
            model_name="room", old_name="update", new_name="update_at",
        ),
    ]
