databases:
  - name: airbnbclone
    databaseName: airbnbclone
    user: airbnbclone
    region: korea

services:
  - type: web
    name: airbnbClone
    env: python
    region: korea
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbclone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
